### ISSUE TITLE
Activate jedi hover on key press

### ISSUE THREAD

**Issue by matteobolner** [mjrodgers/pulsar-ide-python#10]
Hi, 
this might be the place to ask this question, so if that's a problem let me know.
First of all thank you for this package, I have switched from atom to pulsar and this is making my life easier.
I wanted to ask if it is possible to disable jedi hover and activate it on a key press or something like that;
I ask this because most of the time when hovering over variables, functions etc I don't need to see the definition, but it is shown anyways and it's cluttering the workspace. 
Ideally, I would like the possibility to show definition on hovering with something like a key combination; do you know if this function exists?
Alternatively, do you have any suggestions for where to look? 
Thanks again!!
Matteo

**Comment by mjrodgers** [comment]
Sorry to take so long to look at this!

There is actually an easy (but nonintuitive) solution to this: in the settings for the python package, you want to make sure you leave `Jedi Hover` set to `on`. Then there is a keyboard shortcut for the `atom-ide-datatip` package, that will let you turn the tip on and off (for my mac the default is `opt-cmd`).
